{{- if and .Values.gitops.enabled .Values.gitops.serviceAccount.create (not (include "olake.jobServiceAccountName" .)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "olake.uiServiceAccountName" . }}
  namespace: {{ include "olake.namespace" . }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    app.kubernetes.io/component: olake-ui
  {{- with .Values.gitops.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
