apiVersion: v1
kind: Service
metadata:
  name: olake-ui
  namespace: {{ include "olake.namespace" . }}
  {{- with (.Values.olakeUI.service.annotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    {{- include "olake.ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.olakeUI.service.type }}
  ports:
  - port: {{ .Values.olakeUI.env.HTTP_PORT | default "8000" | int }}
    targetPort: olake-ui
    protocol: TCP
    name: olake-ui
    {{- if eq .Values.olakeUI.service.type "NodePort" }}
    nodePort: 30082
    {{- end }}
  selector:
    {{- include "olake.selectorLabels" . | nindent 4 }}
    {{- include "olake.ui.labels" . | nindent 4 }}
