{{- if .Values.fusion.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "olake.fullname" . }}-fusion-config
  namespace: {{ include "olake.namespace" . }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    app.kubernetes.io/component: fusion
data:
  config.yaml: |
    ams:
      server-expose-host: "127.0.0.1"

      thrift-server:
        table-service:
          bind-port: 1260
        optimizing-service:
          bind-port: 1261

      http-server:
        bind-port: 1630

      optimizer:
        task-execute-timeout: 1h
        max-planning-parallelism: {{ .Values.fusion.optimizer.spark.desiredParallelism }}
        bootstrap:
          group-name: spark-container

      {{- if or .Values.fusion.shade.identifier .Values.fusion.shade.sensitiveKeywords }}
      shade:
        {{- if .Values.fusion.shade.identifier }}
        identifier: {{ .Values.fusion.shade.identifier }}
        {{- end }}
        {{- if .Values.fusion.shade.sensitiveKeywords }}
        sensitive-keywords: {{ .Values.fusion.shade.sensitiveKeywords }}
        {{- end }}
      {{- end }}

      database:
        type: postgres
        jdbc-driver-class: org.postgresql.Driver
        url: >-
          {{- if .Values.postgresql.enabled }}
            {{ printf "jdbc:postgresql://postgresql:5432/fusion" }}
          {{- else }}
            {{- $externalPg := .Values.postgresql.external.properties }}
            {{ printf "jdbc:postgresql://%s:%s/%s" $externalPg.host ($externalPg.port | toString) $externalPg.fusion_database }}
          {{- end }}

      terminal:
        local:
          using-session-catalog-for-hive: false
          spark.sql.iceberg.handle-timestamp-without-timezone: false
          spark.sql.codegen.wholeStage: false

{{- end }}
