{{- if .Values.fusion.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "olake.fullname" . }}-fusion-config
  namespace: {{ include "olake.namespace" . }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    app.kubernetes.io/component: fusion
data:
  config.yaml: |
    ams:
      admin-username: {{ .Values.fusion.adminUser }}
      admin-password: {{ .Values.fusion.adminPassword }}
      server-bind-host: {{ .Values.fusion.bindHost | quote }}
      server-expose-host: {{ .Values.fusion.exposeHost | quote }}

      thrift-server:
        max-message-size: 100MB
        selector-thread-count: 2
        selector-queue-size: 4
        table-service:
          bind-port: {{ .Values.fusion.server.table.port }}
          worker-thread-count: 20
        optimizing-service:
          bind-port: {{ .Values.fusion.server.optimizing.port }}

      http-server:
        session-timeout: 7d
        bind-port: {{ .Values.fusion.server.rest.port }}
        rest-auth-type: token

      refresh-external-catalogs:
        interval: 3min
        thread-count: 10
        queue-size: 1000000

      refresh-tables:
        thread-count: 10
        interval: 1min
        max-pending-partition-count: 100

      self-optimizing:
        commit-thread-count: 10
        runtime-data-keep-days: 30
        runtime-data-expire-interval-hours: 1
        refresh-group-interval: 30s

      optimizer:
        heart-beat-timeout: 1min
        task-ack-timeout: 30s
        task-execute-timeout: 1h
        polling-timeout: 3s
        max-planning-parallelism: 1

      blocker:
        timeout: 1min

      expire-snapshots:
        enabled: true
        thread-count: 10

      clean-orphan-files:
        enabled: true
        thread-count: 10
        interval: 1d

      clean-dangling-delete-files:
        enabled: true
        thread-count: 10

      sync-hive-tables:
        enabled: false
        thread-count: 10

      data-expiration:
        enabled: true
        thread-count: 10
        interval: 1d

      auto-create-tags:
        enabled: true
        thread-count: 3
        interval: 1min

      table-manifest-io:
        thread-count: 20

      catalog-meta-cache:
        expiration-interval: 60s

      shade:
        identifier: default
        sensitive-keywords: admin-password;database.password

      overview-cache:
        refresh-interval: 3min
        max-size: 3360

      database:
        type: postgres
        jdbc-driver-class: org.postgresql.Driver
        url: >-
          {{- if .Values.postgresql.enabled }}
            {{ printf "jdbc:postgresql://postgresql:5432/fusion" }}
          {{- else }}
            {{- $externalPg := .Values.postgresql.external.properties }}
            {{ printf "jdbc:postgresql://%s:%s/%s" $externalPg.host $externalPg.port $externalPg.fusion_database }}
          {{- end }}
        username: >-
          {{- if .Values.postgresql.enabled }}
            {{ .Values.postgresql.auth.postgresUser }}
          {{- else }}
            {{- $externalPg := .Values.postgresql.external.properties }}
            {{ $externalPg.username }}
          {{- end }}
        password: >-
          {{- if .Values.postgresql.enabled }}
            {{ .Values.postgresql.auth.postgresPassword }}
          {{- else }}
            {{- $externalPg := .Values.postgresql.external.properties }}
            {{ $externalPg.password }}
          {{- end }}
        connection-pool-max-total: 20
        connection-pool-max-idle: 16
        connection-pool-max-wait-millis: 30000
        auto-create-tables: true

      terminal:
        backend: local
        result:
          limit: 1000
        stop-on-error: false
        session:
          timeout: 30min
        local:
          using-session-catalog-for-hive: false
          spark.sql.iceberg.handle-timestamp-without-timezone: false
          spark.sql.codegen.wholeStage: false

    containers:
      {{- if .Values.fusion.optimizer.spark.enabled }}
      - name: sparkContainer
        container-impl: org.apache.amoro.server.manager.SparkOptimizerContainer
        properties:
          job-uri: {{ .Values.fusion.optimizer.spark.jobUri | quote }}
          spark-conf.spark.kubernetes.container.image: "{{ .Values.fusion.optimizer.spark.image.repository }}:{{ .Values.fusion.optimizer.spark.image.tag }}"
          spark-conf.spark.kubernetes.container.image.pullPolicy: "{{ .Values.fusion.optimizer.spark.image.pullPolicy }}"
          spark-conf.spark.kubernetes.namespace: {{ include "olake.namespace" . | quote }}
          spark-conf.spark.kubernetes.authenticate.driver.serviceAccountName: "{{ include "olake.fusionServiceAccountName" . }}"
          spark-conf.spark.kubernetes.authenticate.executor.serviceAccountName: "{{ include "olake.fusionServiceAccountName" . }}"
          {{- range $key, $value := .Values.fusion.optimizer.spark.extraConfig }}
          {{ printf "spark-conf.%s" $key }}: "{{ $value }}"
          {{- end }}
          {{- range $key, $value := .Values.fusion.optimizer.spark.properties }}
          {{ $key }}: "{{ $value }}"
          {{- end }}
      {{- end }}

{{- end }}
