{{- if and .Values.fusion.enabled (not .Values.olakeUI.initUser.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "olake.fullname" . }}-fusion
  namespace: {{ include "olake.namespace" . }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    app.kubernetes.io/component: fusion
type: Opaque
data:
  AdminUsername: {{ .Values.olakeUI.initUser.adminUser.username | b64enc | quote }}
  AdminPassword: {{ .Values.olakeUI.initUser.adminUser.password | b64enc | quote }}
{{- end }}
