{{- if .Values.fusion.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "olake.fullname" . }}-fusion-rest
  namespace: {{ include "olake.namespace" . }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    app.kubernetes.io/component: fusion
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 1630
      targetPort: 1630
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "olake.name" . }}-fusion
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "olake.fullname" . }}-fusion-table
  namespace: {{ include "olake.namespace" . }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    app.kubernetes.io/component: fusion
spec:
  type: ClusterIP
  ports:
    - name: table
      port: 1260
      targetPort: 1260
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "olake.name" . }}-fusion
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "olake.fullname" . }}-fusion-optimizing
  namespace: {{ include "olake.namespace" . }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    app.kubernetes.io/component: fusion
spec:
  type: ClusterIP
  ports:
    - name: optimizing
      port: 1261
      targetPort: 1261
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "olake.name" . }}-fusion
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}