{{- if and (not .Values.temporal.enabled) (not .Values.temporal.external.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "olake.temporal.secretName" . }}
  namespace: {{ include "olake.namespace" . }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.temporal.external.properties }}
  {{ $.Values.temporal.external.secretKeys.TEMPORAL_ADDRESS | default "TEMPORAL_ADDRESS" }}: {{ .TEMPORAL_ADDRESS | quote }}
  {{ $.Values.temporal.external.secretKeys.TEMPORAL_API_KEY | default "TEMPORAL_API_KEY" }}: {{ .TEMPORAL_API_KEY | quote }}
  {{ $.Values.temporal.external.secretKeys.TEMPORAL_ENABLE_TLS | default "TEMPORAL_ENABLE_TLS" }}: {{ .TEMPORAL_ENABLE_TLS | quote }}
  {{ $.Values.temporal.external.secretKeys.TEMPORAL_EXTERNAL | default "TEMPORAL_EXTERNAL" }}: {{ .TEMPORAL_EXTERNAL | quote }}
  {{ $.Values.temporal.external.secretKeys.TEMPORAL_NAMESPACE | default "TEMPORAL_NAMESPACE" }}: {{ .TEMPORAL_NAMESPACE | quote }}
  {{ $.Values.temporal.external.secretKeys.TEMPORAL_TASK_QUEUE | default "TEMPORAL_TASK_QUEUE" }}: {{ .TEMPORAL_TASK_QUEUE | quote }}
  {{- end }}
{{- end }}
