apiVersion: v1
kind: ConfigMap
metadata:
  name: olake-global-env
  namespace: {{ include "olake.namespace" . }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.global.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- $storageMode := include "olake.storageMode" . }}
  OLAKE_STORAGE_MODE: {{ $storageMode | quote }}
  {{- if eq $storageMode "s3" }}
  {{- include "olake.storageEnv" . | nindent 2 }}
  {{- end }}
