apiVersion: v2
name: postgresql
description: PostgreSQL instance backing the OLake and Fusion charts
type: application
version: 0.0.1
appVersion: "14"
home: https://github.com/datazip-inc/olake-helm
sources:
  - https://github.com/datazip-inc/olake-helm
keywords:
  - postgresql
  - database
  - kubernetes
  - olake
maintainers:
  - name: Team OLake
    email: hello@olake.io
dependencies: []
