apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ include "olake.namespace" . }}
  {{- with ((.Values.elasticsearch.service).annotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    {{- include "olake.elasticsearch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
    name: http
  selector:
    {{- include "olake.selectorLabels" . | nindent 4 }}
    {{- include "olake.elasticsearch.labels" . | nindent 4 }}
