apiVersion: v1
kind: ConfigMap
metadata:
  name: smoke-job
  labels:
    olake.io/managed: "true"
    olake.io/kind: job
data:
  projectId: "123"
  userId: "1"
  config: |
    {
      "name": "smoke-job",
      "source": "smoke-source-test_1",
      "destination": "smoke-dest",
      "frequency": "0 */6 * * *",
      "activate": true
    }
