{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fusion.auth.secretName" . }}
  namespace: {{ include "fusion.namespace" . }}
  labels:
    {{- include "fusion.labels" . | nindent 4 }}
    app.kubernetes.io/component: fusion
type: Opaque
data:
  {{ .Values.auth.secretKeys.username }}: {{ .Values.auth.adminUser.username | b64enc | quote }}
  {{ .Values.auth.secretKeys.password }}: {{ .Values.auth.adminUser.password | b64enc | quote }}
{{- end }}
