{{- /*
TODO: Remove the Helm hook logic in a future release (e.g. v1.0.0).
*/ -}}
{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.secretName" . }}
  namespace: {{ include "postgresql.namespace" . }}
  annotations:
    {{- if not .Values.useStandardResources }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end }}
  labels:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ include "postgresql.host" . | b64enc }}
  port: {{ "5432" | b64enc }}
  {{- range $key, $db := .Values.databases }}
  {{ $key }}: {{ $db | b64enc }}
  {{- end }}
  username: {{ .Values.auth.postgresUser | b64enc }}
  password: {{ .Values.auth.postgresPassword | b64enc }}
  ssl_mode: {{ .Values.auth.sslMode | default "disable" | b64enc }}
{{- end }}
