name: Olake Worker Build And Release
on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to build (master, staging, dev)"
        required: true
        default: ""
        type: string
      version:
        description: "Version to release"
        required: true
        default: ""
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to build (master, staging, dev)"
        required: true
        default: "dev"
        type: choice
        options:
          - master
          - staging
          - dev
      version:
        description: "Version to release"
        required: true
        default: "v0.0.0.dev"
        type: string

jobs:
  build_and_publish_frontend:
    name: Build and publish K8s Worker image for ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      DOCKER_LOGIN: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      K8S_REPO_WORKER: ${{ secrets.K8S_REPO_WORKER || 'olakego' }}
      ENVIRONMENT: ${{ inputs.environment }}
      VERSION: ${{ inputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.environment == 'master' && 'refs/heads/master' || inputs.environment == 'staging' && 'refs/heads/staging' || github.ref }}

      - name: Setup environment variables
        run: |
          echo "ENVIRONMENT=${{ env.ENVIRONMENT }}" >> $GITHUB_ENV
          echo "VERSION=${{ env.VERSION }}" >> $GITHUB_ENV
          echo "Building frontend application for $ENVIRONMENT with version $VERSION"

      - name: Run Release tool
        run: |
          chmod +x ./worker/release.sh
          ./worker/release.sh
        shell: bash