name: Publish Helm Chart

on:
  push:
    branches:
      - master
    paths:
      - 'helm/**'

jobs:
  release:
    permissions:
      contents: write   # needed to push to gh-pages and create releases
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Copy index.html to gh-pages
        run: |
          # Make sure gh-pages exists locally
          git fetch origin gh-pages:gh-pages || true
          if ! git rev-parse --verify gh-pages >/dev/null 2>&1; then
            git switch --orphan gh-pages
            git reset --hard
          else
            git checkout gh-pages
          fi

          # Copy index.html from master branch
          git checkout origin/master -- index.html

          # Commit and push
          git add index.html
          git commit -m "Update index.html from master" || echo "No changes to commit"
          git push origin gh-pages
  