{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "olake.fullname" . }}-postgresql-secret
  namespace: {{ include "olake.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
    {{- include "olake.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ printf "postgresql.%s.svc.cluster.local" (include "olake.namespace" .) | b64enc }}
  port: {{ "5432" | b64enc }}
  database: {{ (.Values.postgresql.auth.postgresDatabase | default "temporal") | b64enc }}
  username: {{ .Values.postgresql.auth.postgresUser | b64enc }}
  password: {{ .Values.postgresql.auth.postgresPassword | b64enc }}
  ssl_mode: {{ "disable" | b64enc }}
{{- end }}