apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: {{ include "olake.namespace" . }}
  {{- with ((.Values.postgresql.service).annotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    {{- include "olake.postgresql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    {{- include "olake.selectorLabels" . | nindent 4 }}
    {{- include "olake.postgresql.labels" . | nindent 4 }}
